"""Add risk fields to Trade model

Revision ID: 261e17baa3d6
Revises: 
Create Date: 2025-06-13 18:38:32.253635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261e17baa3d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('r_multiple', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('setup_tag', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('review_notes')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('setup_tag')
        batch_op.drop_column('r_multiple')
        batch_op.drop_column('risk_amount')

    # ### end Alembic commands ###
