"""Add failure reasons to trade model

Revision ID: a3d50c6b0156
Revises: 261e17baa3d6
Create Date: 2025-06-14 16:28:44.844195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d50c6b0156'
down_revision = '261e17baa3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failure_reasons', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('failure_reasons')

    # ### end Alembic commands ###
