"""Add success_reasons column to trades

Revision ID: e6c9b17fd717
Revises: a3d50c6b0156
Create Date: 2025-06-14 17:42:25.233761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c9b17fd717'
down_revision = 'a3d50c6b0156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success_reasons', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('success_reasons')

    # ### end Alembic commands ###
